#!/bin/bash

# AI Assistant User Identification Test Script
# This script tests the AI assistant's ability to identify and use current user information

echo "👤 Testing AI Assistant User Identification"
echo "========================================="

# Set base URL
BASE_URL="http://localhost:5173"

echo ""
echo "🎯 Test Scenarios for User Identification:"
echo "1. AI should identify current logged-in user"
echo "2. AI should provide personalized responses using user's data"
echo "3. AI should respect data access restrictions based on user permissions"
echo "4. AI should use user's leave balances and history in responses"
echo ""

echo "📋 Sample Test Questions for Staff Users:"
echo "=========================================="
echo ""

questions=(
    "What is my current leave balance?"
    "How many vacation days do I have left?"
    "Am I currently on leave?"
    "Show me my recent leave requests"
    "What's my sick leave balance?"
    "Can I take leave next month?"
    "How many leave days have I used this year?"
    "What's the annual leave policy?"
    "When should I schedule my vacation?"
)

for i in "${!questions[@]}"; do
    echo "$((i+1)). ${questions[$i]}"
done

echo ""
echo "🔍 Expected AI Behavior:"
echo "========================"
echo ""
echo "✅ User Identification:"
echo "   - AI should know the current user's name, department, and staff ID"
echo "   - AI should access the user's personal leave balances"
echo "   - AI should reference the user's current leave status"
echo ""
echo "✅ Personalized Responses:"
echo "   - 'Your current annual leave balance is X days'"
echo "   - 'You have used X days of your Y leave allocation'"
echo "   - 'You are not currently on leave'"
echo "   - 'Your recent leave requests show...'"
echo ""
echo "✅ Data Access Control:"
echo "   - Staff users: Only see their own data"
echo "   - Manager users: See department + their own data"
echo "   - HR/Admin users: See all data"
echo ""
echo "🧪 Manual Testing Steps:"
echo "========================"
echo ""
echo "1. Start the application: npm run dev"
echo ""
echo "2. Test with different user types:"
echo ""
echo "   STAFF USER:"
echo "   - Login with a staff account"
echo "   - Go to $BASE_URL/ai-assistant"
echo "   - Ask: 'What is my leave balance?'"
echo "   - Expected: Personalized response with their actual balance"
echo "   - Ask: 'How many staff are on leave?'"
echo "   - Expected: Declined or redirected to general info"
echo ""
echo "   MANAGER USER:"
echo "   - Login with a manager account"
echo "   - Ask: 'Show me my team's leave patterns'"
echo "   - Expected: Department-level analytics"
echo ""
echo "   HR USER:"
echo "   - Login with an HR account"
echo "   - Ask: 'Show company-wide leave statistics'"
echo "   - Expected: Full company analytics"
echo ""
echo "3. Verify Personalization:"
echo "   - AI should use the user's actual name"
echo "   - AI should reference their actual department"
echo "   - AI should use their real leave balance numbers"
echo "   - AI should know their current leave status"
echo ""
echo "4. Test Data Restrictions:"
echo "   - Try to access other staff data with staff account"
echo "   - Expected: Polite refusal for privacy reasons"
echo "   - Try company-wide queries with staff account"
echo "   - Expected: Redirected to general policies or personal data only"
echo ""
echo "🔧 Technical Implementation:"
echo "=========================="
echo ""
echo "The AI assistant now:"
echo "1. Fetches current user details on every request"
echo "2. Includes user information in AI prompts"
echo "3. Personalizes responses based on user data"
echo "4. Enforces permission-based data filtering"
echo "5. Maintains privacy and security standards"
echo ""
echo "📊 User Data Available to AI:"
echo "=============================="
echo "- Name, Staff ID, Email, Department"
echo "- Current leave balances for all leave types"
echo "- Recent leave requests and history"
echo "- Current active leave (if any)"
echo "- Leave patterns and preferences"
echo ""
echo "✨ Implementation Complete!"
echo "The AI assistant now properly identifies current users and provides personalized responses based on their actual data."
